Bump the devdependencies group with 3 updates (#299)
Bumps the devdependencies group with 3 updates:
[@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin),
[@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser)
and [prettier](https://github.com/prettier/prettier).

Updates `@typescript-eslint/eslint-plugin` from 6.18.1 to 6.19.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/typescript-eslint/typescript-eslint/releases"><code>@​typescript-eslint/eslint-plugin</code>'s
releases</a>.</em></p>
<blockquote>
<h2>v6.19.0</h2>
<h2>6.19.0 (2024-01-15)</h2>
<h3>🚀 Features</h3>
<ul>
<li><strong>eslint-plugin:</strong> [prefer-promise-reject-errors] add
rule (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8011">#8011</a>)</li>
<li><strong>eslint-plugin:</strong> [no-array-delete] add new rule (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8067">#8067</a>)</li>
<li><strong>eslint-plugin:</strong> [no-useless-template-literals] add
fix suggestions (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8065">#8065</a>)</li>
</ul>
<h3>🩹 Fixes</h3>
<ul>
<li><strong>eslint-plugin:</strong> [no-unnecessary-type-assertion]
detect unnecessary non-null-assertion on a call expression (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8143">#8143</a>)</li>
<li><strong>eslint-plugin:</strong> [no-unnecesary-type-assertion] treat
unknown/any as nullable (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8089">#8089</a>)</li>
<li><strong>typescript-estree:</strong> add JSDocParsingMode enum merge
for typescript/lib/tsserverlibrary (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8193">#8193</a>)</li>
<li><strong>typescript-estree:</strong> disallow <code>using</code> as
the variable keyword for <code>for..in</code> loops (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/7649">#7649</a>)</li>
<li><strong>typescript-estree:</strong> fix incorrect backwards-compat
augmentation in TS 5.3 (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8181">#8181</a>)</li>
</ul>
<h3>❤️  Thank You</h3>
<ul>
<li>auvred <a
href="https://github.com/auvred"><code>@​auvred</code></a></li>
<li>Brad Zacher <a
href="https://github.com/bradzacher"><code>@​bradzacher</code></a></li>
<li>Josh Goldberg ✨</li>
<li>Joshua Chen</li>
<li>LJX <a
href="https://github.com/lvjiaxuan"><code>@​lvjiaxuan</code></a></li>
<li>Steven <a
href="https://github.com/Solo-steven"><code>@​Solo-steven</code></a></li>
<li>StyleShit <a
href="https://github.com/StyleShit"><code>@​StyleShit</code></a></li>
</ul>
<p>You can read about our <a
href="https://main--typescript-eslint.netlify.app/users/versioning">versioning
strategy</a> and <a
href="https://main--typescript-eslint.netlify.app/users/releases">releases</a>
on our website.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/CHANGELOG.md"><code>@​typescript-eslint/eslint-plugin</code>'s
changelog</a>.</em></p>
<blockquote>
<h2>6.19.0 (2024-01-15)</h2>
<h3>🚀 Features</h3>
<ul>
<li>
<p><strong>eslint-plugin:</strong> [prefer-promise-reject-errors] add
rule</p>
</li>
<li>
<p><strong>eslint-plugin:</strong> [no-array-delete] add new rule</p>
</li>
<li>
<p><strong>eslint-plugin:</strong> [no-useless-template-literals] add
fix suggestions</p>
</li>
</ul>
<h3>🩹 Fixes</h3>
<ul>
<li>
<p><strong>eslint-plugin:</strong> [no-unnecessary-type-assertion]
detect unnecessary non-null-assertion on a call expression</p>
</li>
<li>
<p><strong>eslint-plugin:</strong> [no-unnecesary-type-assertion] treat
unknown/any as nullable</p>
</li>
</ul>
<h3>❤️  Thank You</h3>
<ul>
<li>auvred</li>
<li>Brad Zacher</li>
<li>Josh Goldberg ✨</li>
<li>Joshua Chen</li>
<li>LJX</li>
<li>Steven</li>
<li>StyleShit</li>
</ul>
<p>You can read about our <a
href="https://main--typescript-eslint.netlify.app/users/versioning">versioning
strategy</a> and <a
href="https://main--typescript-eslint.netlify.app/users/releases">releases</a>
on our website.</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/7c673a146d26d4360a25638f901a3c329bcca8c4"><code>7c673a1</code></a>
chore(release): publish 6.19.0</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/85ae4a8977149583b0c501e092a927b1435e68d2"><code>85ae4a8</code></a>
fix(eslint-plugin): [no-unnecesary-type-assertion] treat unknown/any as
nulla...</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/5a5670800fda2cd5ffd060b0fb9db351f0f3c4d8"><code>5a56708</code></a>
fix(eslint-plugin): [no-unnecessary-type-assertion] detect unnecessary
non-nu...</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/c3767edf65716be08df25723d7dbb770de0e7037"><code>c3767ed</code></a>
feat(eslint-plugin): [no-useless-template-literals] add fix suggestions
(<a
href="https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin/issues/8065">#8065</a>)</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/8ca5e5e8430ba1beb5f12f317d403d7087bf9210"><code>8ca5e5e</code></a>
docs: force space after await in no-floating-promises snippet (<a
href="https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin/issues/8228">#8228</a>)</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/e0f591e9d299a42bcf2087200b0770d810af2e64"><code>e0f591e</code></a>
feat(eslint-plugin): [no-array-delete] add new rule (<a
href="https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin/issues/8067">#8067</a>)</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/1aa8664bab1f7ea77539ec83f65123e8ebe34b39"><code>1aa8664</code></a>
feat(eslint-plugin): [prefer-promise-reject-errors] add rule (<a
href="https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin/issues/8011">#8011</a>)</li>
<li>See full diff in <a
href="https://github.com/typescript-eslint/typescript-eslint/commits/v6.19.0/packages/eslint-plugin">compare
view</a></li>
</ul>
</details>
<br />

Updates `@typescript-eslint/parser` from 6.18.1 to 6.19.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/typescript-eslint/typescript-eslint/releases"><code>@​typescript-eslint/parser</code>'s
releases</a>.</em></p>
<blockquote>
<h2>v6.19.0</h2>
<h2>6.19.0 (2024-01-15)</h2>
<h3>🚀 Features</h3>
<ul>
<li><strong>eslint-plugin:</strong> [prefer-promise-reject-errors] add
rule (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8011">#8011</a>)</li>
<li><strong>eslint-plugin:</strong> [no-array-delete] add new rule (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8067">#8067</a>)</li>
<li><strong>eslint-plugin:</strong> [no-useless-template-literals] add
fix suggestions (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8065">#8065</a>)</li>
</ul>
<h3>🩹 Fixes</h3>
<ul>
<li><strong>eslint-plugin:</strong> [no-unnecessary-type-assertion]
detect unnecessary non-null-assertion on a call expression (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8143">#8143</a>)</li>
<li><strong>eslint-plugin:</strong> [no-unnecesary-type-assertion] treat
unknown/any as nullable (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8089">#8089</a>)</li>
<li><strong>typescript-estree:</strong> add JSDocParsingMode enum merge
for typescript/lib/tsserverlibrary (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8193">#8193</a>)</li>
<li><strong>typescript-estree:</strong> disallow <code>using</code> as
the variable keyword for <code>for..in</code> loops (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/7649">#7649</a>)</li>
<li><strong>typescript-estree:</strong> fix incorrect backwards-compat
augmentation in TS 5.3 (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8181">#8181</a>)</li>
</ul>
<h3>❤️  Thank You</h3>
<ul>
<li>auvred <a
href="https://github.com/auvred"><code>@​auvred</code></a></li>
<li>Brad Zacher <a
href="https://github.com/bradzacher"><code>@​bradzacher</code></a></li>
<li>Josh Goldberg ✨</li>
<li>Joshua Chen</li>
<li>LJX <a
href="https://github.com/lvjiaxuan"><code>@​lvjiaxuan</code></a></li>
<li>Steven <a
href="https://github.com/Solo-steven"><code>@​Solo-steven</code></a></li>
<li>StyleShit <a
href="https://github.com/StyleShit"><code>@​StyleShit</code></a></li>
</ul>
<p>You can read about our <a
href="https://main--typescript-eslint.netlify.app/users/versioning">versioning
strategy</a> and <a
href="https://main--typescript-eslint.netlify.app/users/releases">releases</a>
on our website.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/parser/CHANGELOG.md"><code>@​typescript-eslint/parser</code>'s
changelog</a>.</em></p>
<blockquote>
<h2>6.19.0 (2024-01-15)</h2>
<p>This was a version bump only for parser to align it with other
projects, there were no code changes.</p>
<p>You can read about our <a
href="https://main--typescript-eslint.netlify.app/users/versioning">versioning
strategy</a> and <a
href="https://main--typescript-eslint.netlify.app/users/releases">releases</a>
on our website.</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/7c673a146d26d4360a25638f901a3c329bcca8c4"><code>7c673a1</code></a>
chore(release): publish 6.19.0</li>
<li>See full diff in <a
href="https://github.com/typescript-eslint/typescript-eslint/commits/v6.19.0/packages/parser">compare
view</a></li>
</ul>
</details>
<br />

Updates `prettier` from 3.2.2 to 3.2.4
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/releases">prettier's
releases</a>.</em></p>
<blockquote>
<h2>3.2.4</h2>
<ul>
<li>Fix <code>.eslintrc.json</code> format <a
href="https://redirect.github.com/prettier/prettier/issues/15947">#15947</a></li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#324">Changelog</a></p>
<h2>3.2.3</h2>
<ul>
<li>Format <code>tsconfig.json</code> file with <code>jsonc</code>
parser <a
href="https://redirect.github.com/prettier/prettier/issues/15927">#15927</a></li>
</ul>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#323">Changelog</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's
changelog</a>.</em></p>
<blockquote>
<h1>3.2.4</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.2.3...3.2.4">diff</a></p>
<h4>Fix incorrect parser inference (<a
href="https://redirect.github.com/prettier/prettier/pull/15947">#15947</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>)</h4>
<p>Files like <code>.eslintrc.json</code> were incorrectly formatted as
JSONC files.</p>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
prettier --file-info .eslintrc.json
{ &quot;ignored&quot;: false, &quot;inferredParser&quot;:
&quot;jsonc&quot; }
<p>// Prettier 3.2.4
prettier --file-info .eslintrc.json
{ &quot;ignored&quot;: false, &quot;inferredParser&quot;:
&quot;json&quot; }
</code></pre></p>
<h1>3.2.3</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.2.2...3.2.3">diff</a></p>
<h4>Throw errors for invalid code (<a
href="https://redirect.github.com/prettier/prettier/pull/15881">#15881</a>
by <a href="https://github.com/fisker"><code>@​fisker</code></a>, <a
href="https://github.com/Josh-Cena"><code>@​Josh-Cena</code></a>, <a
href="https://github.com/auvred"><code>@​auvred</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="ts"><code>// Input
1++;
<p>// Prettier 3.2.2
1++;</p>
<p>// Prettier 3.2.3
SyntaxError: Invalid left-hand side expression in unary operation (1:1)
&gt; 1 | 1++;
| ^
</code></pre></p>
<!-- raw HTML omitted -->
<pre lang="ts"><code>// Input
try {} catch (error = 1){}

// Prettier 3.2.2
try {
} catch (error) {}

// Prettier 3.2.3
SyntaxError: Catch clause variable cannot have an initializer. (1:23)
&lt;/tr&gt;&lt;/table&gt; 
</code></pre>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prettier/prettier/commit/03822f5b3428ad77781ede5bd41a248b465be3cd"><code>03822f5</code></a>
Release 3.2.4</li>
<li><a
href="https://github.com/prettier/prettier/commit/1cd4d9c1605e7344e6c0735c1c6cb51ad620b01d"><code>1cd4d9c</code></a>
Fix JSONC filenames list (<a
href="https://redirect.github.com/prettier/prettier/issues/15947">#15947</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/6c6a332171f590a38c369673662d1a5baf765167"><code>6c6a332</code></a>
Spellcheck</li>
<li><a
href="https://github.com/prettier/prettier/commit/75ec1f792123f42f943fad605236d14a7b02f8c1"><code>75ec1f7</code></a>
Fix lock file</li>
<li><a
href="https://github.com/prettier/prettier/commit/dda00cdd1d602e6034d0dbdac7ee84fc3b32f3a9"><code>dda00cd</code></a>
Clean changelog_unreleased</li>
<li><a
href="https://github.com/prettier/prettier/commit/c12e3c67f93d637cacd2e2a2430f97103abe1276"><code>c12e3c6</code></a>
Git blame ignore 3.2.3</li>
<li><a
href="https://github.com/prettier/prettier/commit/4985be553e911fef7d83f3341eb143c443473c58"><code>4985be5</code></a>
Bump Prettier dependency to 3.2.3</li>
<li><a
href="https://github.com/prettier/prettier/commit/38c0d212e78e645f6c64b88fc6a5847013bc837e"><code>38c0d21</code></a>
Update dependents count</li>
<li><a
href="https://github.com/prettier/prettier/commit/42ba4373f47a67a5d50756a76a57b2ce3a5524e5"><code>42ba437</code></a>
Release 3.2.3</li>
<li><a
href="https://github.com/prettier/prettier/commit/99c873d4219f02f684ec8f3d200abee04e9bbe85"><code>99c873d</code></a>
chore(deps): update typescript-eslint to v6.19.0 (<a
href="https://redirect.github.com/prettier/prettier/issues/15939">#15939</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/prettier/prettier/compare/3.2.2...3.2.4">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>