Bump the devdependencies group with 4 updates (#298)
Bumps the devdependencies group with 4 updates:
[@typescript-eslint/eslint-plugin](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin),
[@typescript-eslint/parser](https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser),
[eslint-plugin-n](https://github.com/eslint-community/eslint-plugin-n)
and [prettier](https://github.com/prettier/prettier).

Updates `@typescript-eslint/eslint-plugin` from 6.18.0 to 6.18.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/typescript-eslint/typescript-eslint/releases"><code>@​typescript-eslint/eslint-plugin</code>'s
releases</a>.</em></p>
<blockquote>
<h2>v6.18.1</h2>
<h2>6.18.1 (2024-01-08)</h2>
<h3>🩹 Fixes</h3>
<ul>
<li><strong>eslint-plugin:</strong> [no-non-null-assertion] provide
valid fix when member access is on next line (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8185">#8185</a>)</li>
<li><strong>eslint-plugin:</strong> [no-unnecessary-condition] improve
checking optional callee (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8178">#8178</a>)</li>
<li><strong>eslint-plugin:</strong> [prefer-readonly] support modifiers
of unions and intersections (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8169">#8169</a>)</li>
<li><strong>eslint-plugin:</strong> [switch-exhaustiveness-check] fix
new allowDefaultCaseForExhaustiveSwitch option (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8176">#8176</a>)</li>
<li><strong>typescript-estree:</strong> fix invalid parsing error when
use update expression on non-null assertion (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8202">#8202</a>)</li>
<li><strong>typescript-estree:</strong> only create project service from
env setting if project is enabled (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8136">#8136</a>)</li>
<li><strong>utils:</strong> improve error message on typed rule with
invalid parser (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8146">#8146</a>)</li>
</ul>
<h3>❤️  Thank You</h3>
<ul>
<li>auvred <a
href="https://github.com/auvred"><code>@​auvred</code></a></li>
<li>James <a
href="https://github.com/Zamiell"><code>@​Zamiell</code></a></li>
<li>Josh Goldberg ✨</li>
<li>YeonJuan <a
href="https://github.com/yeonjuan"><code>@​yeonjuan</code></a></li>
</ul>
<p>You can read about our <a
href="https://main--typescript-eslint.netlify.app/users/versioning">versioning
strategy</a> and <a
href="https://main--typescript-eslint.netlify.app/users/releases">releases</a>
on our website.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/CHANGELOG.md"><code>@​typescript-eslint/eslint-plugin</code>'s
changelog</a>.</em></p>
<blockquote>
<h2>6.18.1 (2024-01-08)</h2>
<h3>🩹 Fixes</h3>
<ul>
<li>
<p><strong>eslint-plugin:</strong> [no-non-null-assertion] provide valid
fix when member access is on next line</p>
</li>
<li>
<p><strong>eslint-plugin:</strong> [no-unnecessary-condition] improve
checking optional callee</p>
</li>
<li>
<p><strong>eslint-plugin:</strong> [prefer-readonly] support modifiers
of unions and intersections</p>
</li>
<li>
<p><strong>eslint-plugin:</strong> [switch-exhaustiveness-check] fix new
allowDefaultCaseForExhaustiveSwitch option</p>
</li>
</ul>
<h3>❤️  Thank You</h3>
<ul>
<li>auvred</li>
<li>James</li>
<li>Josh Goldberg ✨</li>
<li>YeonJuan</li>
</ul>
<p>You can read about our <a
href="https://main--typescript-eslint.netlify.app/users/versioning">versioning
strategy</a> and <a
href="https://main--typescript-eslint.netlify.app/users/releases">releases</a>
on our website.</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/aa7ab0ec27907657aa6ff5ec287528adecb12c96"><code>aa7ab0e</code></a>
chore(release): publish 6.18.1</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/78db0add16e9d7ea23c5ffc13341cc13b16eec2d"><code>78db0ad</code></a>
chore: fix test formatting in prefer-readonly.test.ts (<a
href="https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin/issues/8223">#8223</a>)</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/5205192b9fdc83271230ec043274f4da0ec1794a"><code>5205192</code></a>
fix(eslint-plugin): [switch-exhaustiveness-check] fix new
allowDefaultCaseFor...</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/3a219c021e2d7a7570cd25903cad767a4a991572"><code>3a219c0</code></a>
fix(eslint-plugin): [prefer-readonly] support modifiers of unions and
interse...</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/10c0530a960c50edf77adb68d7c101488dfc59ff"><code>10c0530</code></a>
fix(eslint-plugin): [no-unnecessary-condition] improve checking optional
call...</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/27d6ac13d3c6d8061a866a77ded86bccfb878c92"><code>27d6ac1</code></a>
fix(eslint-plugin): [no-non-null-assertion] provide valid fix when
member acc...</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/1ee30876c9572ecffab9dcc7387d4e1eb02cbc4b"><code>1ee3087</code></a>
chore: enable eslint-plugin-jsdoc internally (<a
href="https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/eslint-plugin/issues/8145">#8145</a>)</li>
<li>See full diff in <a
href="https://github.com/typescript-eslint/typescript-eslint/commits/v6.18.1/packages/eslint-plugin">compare
view</a></li>
</ul>
</details>
<br />

Updates `@typescript-eslint/parser` from 6.18.0 to 6.18.1
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/typescript-eslint/typescript-eslint/releases"><code>@​typescript-eslint/parser</code>'s
releases</a>.</em></p>
<blockquote>
<h2>v6.18.1</h2>
<h2>6.18.1 (2024-01-08)</h2>
<h3>🩹 Fixes</h3>
<ul>
<li><strong>eslint-plugin:</strong> [no-non-null-assertion] provide
valid fix when member access is on next line (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8185">#8185</a>)</li>
<li><strong>eslint-plugin:</strong> [no-unnecessary-condition] improve
checking optional callee (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8178">#8178</a>)</li>
<li><strong>eslint-plugin:</strong> [prefer-readonly] support modifiers
of unions and intersections (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8169">#8169</a>)</li>
<li><strong>eslint-plugin:</strong> [switch-exhaustiveness-check] fix
new allowDefaultCaseForExhaustiveSwitch option (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8176">#8176</a>)</li>
<li><strong>typescript-estree:</strong> fix invalid parsing error when
use update expression on non-null assertion (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8202">#8202</a>)</li>
<li><strong>typescript-estree:</strong> only create project service from
env setting if project is enabled (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8136">#8136</a>)</li>
<li><strong>utils:</strong> improve error message on typed rule with
invalid parser (<a
href="https://redirect.github.com/typescript-eslint/typescript-eslint/pull/8146">#8146</a>)</li>
</ul>
<h3>❤️  Thank You</h3>
<ul>
<li>auvred <a
href="https://github.com/auvred"><code>@​auvred</code></a></li>
<li>James <a
href="https://github.com/Zamiell"><code>@​Zamiell</code></a></li>
<li>Josh Goldberg ✨</li>
<li>YeonJuan <a
href="https://github.com/yeonjuan"><code>@​yeonjuan</code></a></li>
</ul>
<p>You can read about our <a
href="https://main--typescript-eslint.netlify.app/users/versioning">versioning
strategy</a> and <a
href="https://main--typescript-eslint.netlify.app/users/releases">releases</a>
on our website.</p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/parser/CHANGELOG.md"><code>@​typescript-eslint/parser</code>'s
changelog</a>.</em></p>
<blockquote>
<h2>6.18.1 (2024-01-08)</h2>
<p>This was a version bump only for parser to align it with other
projects, there were no code changes.</p>
<p>You can read about our <a
href="https://main--typescript-eslint.netlify.app/users/versioning">versioning
strategy</a> and <a
href="https://main--typescript-eslint.netlify.app/users/releases">releases</a>
on our website.</p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/aa7ab0ec27907657aa6ff5ec287528adecb12c96"><code>aa7ab0e</code></a>
chore(release): publish 6.18.1</li>
<li><a
href="https://github.com/typescript-eslint/typescript-eslint/commit/1ee30876c9572ecffab9dcc7387d4e1eb02cbc4b"><code>1ee3087</code></a>
chore: enable eslint-plugin-jsdoc internally (<a
href="https://github.com/typescript-eslint/typescript-eslint/tree/HEAD/packages/parser/issues/8145">#8145</a>)</li>
<li>See full diff in <a
href="https://github.com/typescript-eslint/typescript-eslint/commits/v6.18.1/packages/parser">compare
view</a></li>
</ul>
</details>
<br />

Updates `eslint-plugin-n` from 16.6.1 to 16.6.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/eslint-community/eslint-plugin-n/releases">eslint-plugin-n's
releases</a>.</em></p>
<blockquote>
<h2>Release 16.6.2</h2>
<ul>
<li>fix: no-callback-literal ignore unknown nodes (<a
href="https://redirect.github.com/eslint-community/eslint-plugin-n/issues/163">#163</a>)
(5fc2198)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/eslint-community/eslint-plugin-n/commit/ec5badbca03b8e88c594757e4d5c391370727892"><code>ec5badb</code></a>
Release 16.6.2</li>
<li><a
href="https://github.com/eslint-community/eslint-plugin-n/commit/9ddd351e27f265e69c7d70bdfe3f87729c07a54c"><code>9ddd351</code></a>
chore: update tests to use eslintrc options</li>
<li><a
href="https://github.com/eslint-community/eslint-plugin-n/commit/5fc2198b377e589582f7fc2ab314fb11fc75648a"><code>5fc2198</code></a>
fix: no-callback-literal ignore unknown nodes (<a
href="https://redirect.github.com/eslint-community/eslint-plugin-n/issues/163">#163</a>)</li>
<li><a
href="https://github.com/eslint-community/eslint-plugin-n/commit/c19110141717bd9772ba6410574a9b93d66094e8"><code>c191101</code></a>
chore: add non-rule-change issue template (<a
href="https://redirect.github.com/eslint-community/eslint-plugin-n/issues/159">#159</a>)</li>
<li><a
href="https://github.com/eslint-community/eslint-plugin-n/commit/ad8f4f4fde1c356d1647005498c4709b2bfa4217"><code>ad8f4f4</code></a>
chore: move rule tests parserOptions to ruleTester (<a
href="https://redirect.github.com/eslint-community/eslint-plugin-n/issues/157">#157</a>)</li>
<li>See full diff in <a
href="https://github.com/eslint-community/eslint-plugin-n/compare/16.6.1...16.6.2">compare
view</a></li>
</ul>
</details>
<br />

Updates `prettier` from 3.1.1 to 3.2.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/releases">prettier's
releases</a>.</em></p>
<blockquote>
<h2>3.2.2</h2>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#322">Changelog</a></p>
<h2>3.2.1</h2>
<p>🔗 <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md#321">Changelog</a></p>
<h2>3.2.0</h2>
<p><a
href="https://github.com/prettier/prettier/compare/3.1.1...3.2.0">diff</a></p>
<p>🔗 <a href="https://prettier.io/blog/2024/01/12/3.2.0.html">Release
note</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/prettier/prettier/blob/main/CHANGELOG.md">prettier's
changelog</a>.</em></p>
<blockquote>
<h1>3.2.2</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.2.1...3.2.2">diff</a></p>
<h4>Fix crash when parsing template literal CSS in a JSX style tag using
a spread attribute (<a
href="https://redirect.github.com/prettier/prettier/pull/15896">#15896</a>
by <a href="https://github.com/eelco"><code>@​eelco</code></a>)</h4>
<p>For example this code would crash before:</p>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>&lt;style {...spread}&gt;{`.{}`}&lt;/style&gt;
</code></pre>
<h4>Fix formatting error on optional call expression and member chain
(<a
href="https://redirect.github.com/prettier/prettier/pull/15920">#15920</a>
by <a
href="https://github.com/sosukesuzuki"><code>@​sosukesuzuki</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
a(() =&gt; {}, c?.d());
<p>// Prettier 3.2.1
TypeError: Cannot read properties of undefined (reading 'type')</p>
<p>// Prettier 3.2.2
a(() =&gt; {}, c?.d());
</code></pre></p>
<h1>3.2.1</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.2.0...3.2.1">diff</a></p>
<h4>Fix formatting error on member chain (<a
href="https://redirect.github.com/prettier/prettier/pull/15915">#15915</a>
by <a
href="https://github.com/sosukesuzuki"><code>@​sosukesuzuki</code></a>)</h4>
<!-- raw HTML omitted -->
<pre lang="jsx"><code>// Input
test().test2().test2(thing?.something);
<p>// Prettier 3.2.0
TypeError: Cannot read properties of undefined (reading 'type')</p>
<p>// Prettier 3.2.1
test().test2().test2(thing?.something);</p>
<p></code></pre></p>
<h1>3.2.0</h1>
<p><a
href="https://github.com/prettier/prettier/compare/3.1.1...3.2.0">diff</a></p>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prettier/prettier/commit/5f2c6df4629b1474be5002ff3c6f8ad4a666b70f"><code>5f2c6df</code></a>
Release 3.2.2</li>
<li><a
href="https://github.com/prettier/prettier/commit/cb8004f3f1141635e2a4993ab87d55fbe3b64fb7"><code>cb8004f</code></a>
Fix formatting error on optional call expression and member chain (<a
href="https://redirect.github.com/prettier/prettier/issues/15920">#15920</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/0bfcb2d5a544a09c94a7d6ca637f05271fa270ce"><code>0bfcb2d</code></a>
Fix css embed in JSX when using (only) a spread attribute (<a
href="https://redirect.github.com/prettier/prettier/issues/15896">#15896</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/12ab54898ca2a59826714c3027b8ce037cabdd6d"><code>12ab548</code></a>
Add <code>prettier-plugin-gherkin</code> to the community plugins list
(<a
href="https://redirect.github.com/prettier/prettier/issues/15919">#15919</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/4ce96dd530613b99bb4a682ec93f719f3d4109f5"><code>4ce96dd</code></a>
Fix typo (<a
href="https://redirect.github.com/prettier/prettier/issues/15917">#15917</a>)</li>
<li><a
href="https://github.com/prettier/prettier/commit/08f37968632dc2e72789160704c3f36268bf3c1c"><code>08f3796</code></a>
Run <code>yarn</code></li>
<li><a
href="https://github.com/prettier/prettier/commit/11aea0df1a9708c0c22f6a93b2662c1413f8d783"><code>11aea0d</code></a>
Clean changelog_unreleased</li>
<li><a
href="https://github.com/prettier/prettier/commit/75e66b8c444ec2a251f72917dbe5b58c4a210051"><code>75e66b8</code></a>
Git blame ignore 3.2.1</li>
<li><a
href="https://github.com/prettier/prettier/commit/5811ad00705488365e0d0baf50c92965edddf58e"><code>5811ad0</code></a>
Bump Prettier dependency to 3.2.1</li>
<li><a
href="https://github.com/prettier/prettier/commit/48ad20859bad01bf70ebc27051939c2329c52b18"><code>48ad208</code></a>
Release 3.2.1</li>
<li>Additional commits viewable in <a
href="https://github.com/prettier/prettier/compare/3.1.1...3.2.2">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>